const { chromium } = require('playwright');
const fs = require('fs');
const { execFile } = require('child_process');

const port = 18766;
const dataDir = '/tmp/sticky-sticky-qa-db';
fs.rmSync(dataDir, { recursive: true, force: true });
fs.mkdirSync(dataDir, { recursive: true });
const server = execFile('python3', ['server.py'], { env: { ...process.env, STICKY_STICKY_PORT: String(port), STICKY_STICKY_DATA_DIR: dataDir } });
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const fail = (m) => { throw new Error(m); };
(async () => {
  await sleep(1000);
  const browser = await chromium.launch({ headless: true, executablePath: '/usr/bin/brave-browser' });
  const page = await browser.newPage({ viewport: { width: Number(process.env.QA_WIDTH || 1280), height: Number(process.env.QA_HEIGHT || 800) } });
  const errors = [];
  page.on('pageerror', e => errors.push(String(e)));
  page.on('console', m => { if (m.type() === 'error' && !m.text().includes('404')) errors.push(m.text()); });
  const note = await page.request.post(`http://127.0.0.1:${port}/api/notes`, { data: { title: 'QA note', body: 'persisted', x: 300, y: 240, color: 'yellow' } });
  const stroke = await page.request.post(`http://127.0.0.1:${port}/api/strokes`, { data: { points: [{x:300,y:240},{x:380,y:300}], color: '#625276', width: 6 } });
  if (!note.ok() || !stroke.ok()) fail('fixture preseed failed');
  await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(200);
  if (errors.length) fail('browser errors at 100%: ' + errors.join(' | '));
  const snap = async () => page.evaluate(() => {
    const n = document.querySelector('.note'), p = document.querySelector('.draw path');
    const nr = n.getBoundingClientRect(), pr = p?.getBoundingClientRect(), br = document.querySelector('.board').getBoundingClientRect();
    return { note: {x:nr.x,y:nr.y,w:nr.width,h:nr.height}, stroke: pr && {x:pr.x,y:pr.y,w:pr.width,h:pr.height}, board:{x:br.x,y:br.y,w:br.width,h:br.height}, pct: document.querySelector('.controls b')?.textContent, zoom: [...document.querySelectorAll('.controls b')].at(-1)?.textContent };
  });
  const a = await snap();
  if (!a.stroke) fail('seed stroke not rendered');
  const boardBox = await page.locator('.board').boundingBox();
  await page.getByRole('button', { name: /Marker/ }).click();
  await page.getByRole('button', { name: 'pink' }).click();
  await page.mouse.move(boardBox.x + 500, boardBox.y + 220);
  await page.mouse.down(); await page.mouse.move(boardBox.x + 540, boardBox.y + 245); await page.mouse.up();
  await page.waitForTimeout(150);
  const drawn = await (await page.request.get(`http://127.0.0.1:${port}/api/strokes`)).json();
  if (drawn.length < 2) fail('marker pointer stroke was not persisted');
  await page.reload({ waitUntil: 'networkidle' }); await page.waitForTimeout(150);
  const afterDrawReload = await (await page.request.get(`http://127.0.0.1:${port}/api/strokes`)).json();
  if (afterDrawReload.length !== drawn.length) fail('marker stroke did not survive reload');
  await page.getByRole('button', { name: /Marker/ }).click();
  await page.getByRole('button', { name: 'Eraser' }).click();
  await page.mouse.move(boardBox.x + 500, boardBox.y + 220);
  await page.mouse.down(); await page.mouse.move(boardBox.x + 540, boardBox.y + 245); await page.mouse.up();
  await page.waitForTimeout(150);
  const erased = await (await page.request.get(`http://127.0.0.1:${port}/api/strokes`)).json();
  if (erased.length >= drawn.length) fail('eraser did not remove the intersected stroke without overpaint');
  await page.getByRole('button', { name: '↶ Undo' }).click(); await page.waitForTimeout(150);
  await page.reload({ waitUntil: 'networkidle' }); await page.waitForTimeout(150);
  const afterUndoReload = await (await page.request.get(`http://127.0.0.1:${port}/api/strokes`)).json();
  if (afterUndoReload.length !== drawn.length) fail('undo did not restore stroke state after reload');
  const title = page.locator('.board-title'), subtitle = page.locator('.board-subtitle');
  await title.fill('QA title'); await title.blur();
  await subtitle.fill('QA subtitle'); await subtitle.blur();
  await page.waitForTimeout(150); await page.reload({ waitUntil: 'networkidle' }); await page.waitForTimeout(150);
  if (await title.inputValue() !== 'QA title' || await subtitle.inputValue() !== 'QA subtitle') fail('title/subtitle did not survive reload');
  const noteBefore = await page.locator('.note').boundingBox();
  await page.locator('.note').dispatchEvent('pointerdown', { pointerId: 1, clientX: noteBefore.x + 20, clientY: noteBefore.y + 20, bubbles: true });
  await page.locator('.note').dispatchEvent('pointermove', { pointerId: 1, clientX: noteBefore.x + 80, clientY: noteBefore.y + 60, bubbles: true });
  await page.locator('.note').dispatchEvent('pointerup', { pointerId: 1, clientX: noteBefore.x + 80, clientY: noteBefore.y + 60, bubbles: true });
  await page.waitForTimeout(150); await page.reload({ waitUntil: 'networkidle' }); await page.waitForTimeout(150);
  const moved = await page.locator('.note').boundingBox();
  if (Math.abs(moved.x - noteBefore.x) < 20 || Math.abs(moved.y - noteBefore.y) < 20) fail('note drag did not survive reload');
  const shell = page.locator('.board-shell'), shellBefore = await shell.getAttribute('style');
  const boardNow = await page.locator('.board').boundingBox();
  await page.mouse.move(boardNow.x + boardNow.width / 2, boardNow.y + boardNow.height / 2);
  await page.mouse.down(); await page.mouse.move(boardNow.x + boardNow.width / 2 + 100, boardNow.y + boardNow.height / 2 + 80); await page.mouse.up();
  const shellAfter = await shell.getAttribute('style');
  if (shellBefore === shellAfter) fail('inner hand pan did not move board');
  await page.mouse.move(10, 10); await page.mouse.down(); await page.mouse.move(100, 100); await page.mouse.up();
  if (await shell.getAttribute('style') !== shellAfter) fail('outer background moved board');
  await page.mouse.move(640, 400); await page.mouse.wheel(0, -120);
  await page.waitForTimeout(100);
  const wheelZoomIn = [...await page.locator('.controls b').allTextContents()].at(-1);
  const expectedWheelZoomIn = Math.round(Math.max(0.45, Math.min(1.5, Math.pow(1.0015, 120))) * 100);
  if (Math.abs(parseInt(wheelZoomIn, 10) - expectedWheelZoomIn) > 1) fail('wheel zoom-in display unsynchronized: ' + wheelZoomIn);
  await page.mouse.wheel(0, 100000); await page.waitForTimeout(100);
  const wheelZoomOut = [...await page.locator('.controls b').allTextContents()].at(-1);
  if (wheelZoomOut !== '45%') fail('wheel zoom-out bound failed: ' + wheelZoomOut);
  const currentBoard = await (await page.request.get(`http://127.0.0.1:${port}/api/board`)).json();
  await page.request.put(`http://127.0.0.1:${port}/api/board`, { data: { width: 160000, height: 110000, version: currentBoard.version } });
  await page.reload({ waitUntil: 'networkidle' }); await page.waitForTimeout(250);
  const b = await snap();
  const persisted = await (await page.request.get(`http://127.0.0.1:${port}/api/board`)).json();
  if (persisted.width !== 160000 || persisted.height !== 110000) fail('board dimensions did not persist: ' + JSON.stringify(persisted));
  if (b.board.w <= a.board.w || b.board.h <= a.board.h) fail('board did not grow at 10000%');
  const ratioNote = b.note.w / a.note.w, ratioStroke = b.stroke.w / a.stroke.w;
  if (Math.abs(ratioNote - 1) > 0.08 || Math.abs(ratioStroke - 1) > 0.08)
    fail(`same-zoom world size changed note=${ratioNote} stroke=${ratioStroke}`);
  const { width: viewportWidth, height: viewportHeight } = page.viewportSize();
  const cx = viewportWidth / 2, cy = viewportHeight / 2;
  if (Math.abs((b.board.x + b.board.w/2)-cx) > 8 || Math.abs((b.board.y+b.board.h/2)-cy) > 8) fail('reload camera not centered: ' + JSON.stringify(b.board));
  const zoomPlus = page.locator('.controls button').last(); await zoomPlus.click(); await page.waitForTimeout(100);
  const z = await snap(); if (!(z.note.w > b.note.w && z.stroke.w > b.stroke.w)) fail('zoom did not scale note and stroke');
  console.log(JSON.stringify({ pass:true, at100:a, at10000:b, zoom:z, persisted, errors }));
  await browser.close(); server.kill();
})().catch(e => { console.error(e.stack || e); try { server.kill(); } catch {} process.exitCode = 1; });
