const { chromium } = require('playwright');
const { execFile } = require('child_process');
const fs = require('fs');
const port = 18767, dataDir = '/tmp/sticky-sticky-narrow-qa';
fs.rmSync(dataDir, { recursive: true, force: true }); fs.mkdirSync(dataDir, { recursive: true });
const server = execFile('python3', ['server.py'], { env: { ...process.env, STICKY_STICKY_PORT: String(port), STICKY_STICKY_DATA_DIR: dataDir } });
const sleep = ms => new Promise(r => setTimeout(r, ms));
const fail = m => { throw Error(m); };
(async () => {
  await sleep(500);
  const browser = await chromium.launch({ headless: true, executablePath: '/usr/bin/brave-browser' });
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const note = await page.request.post(`http://127.0.0.1:${port}/api/notes`, { data: { title: 'QA', body: 'keep', x: 300, y: 240, color: 'yellow' } });
  const stroke = await page.request.post(`http://127.0.0.1:${port}/api/strokes`, { data: { points: [{x:300,y:240},{x:380,y:300}], color: '#625276', width: 6 } });
  if (!note.ok() || !stroke.ok()) fail('fixture failed');
  await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'networkidle' });
  const errors = []; page.on('pageerror', e => errors.push(String(e)));
  const snap = () => page.evaluate(() => { const n=document.querySelector('.note').getBoundingClientRect(), p=document.querySelector('.draw path').getBoundingClientRect(), b=document.querySelector('.board').getBoundingClientRect(); return {n:{x:n.x,y:n.y,w:n.width,h:n.height},p:{x:p.x,y:p.y,w:p.width,h:p.height},b:{x:b.x,y:b.y,w:b.width,h:b.height}}; });
  const before = await snap();
  await page.mouse.move(640, 400); await page.mouse.wheel(0, -120); await sleep(250);
  const zoom = await page.locator('.controls b').last().textContent(); if (zoom !== '120%') fail('wheel zoom=' + zoom);
  const cam = await page.evaluate(() => localStorage.getItem('sticky-sticky.camera.v1')); if (!cam) fail('camera not saved');
  await page.reload({ waitUntil: 'networkidle' }); await sleep(250); if (await page.locator('.controls b').last().textContent() !== '120%') fail('camera zoom not restored');
  await page.evaluate(() => localStorage.setItem('sticky-sticky.camera.v1', '{bad')); await page.reload({ waitUntil: 'networkidle' }); if (!await page.locator('.note').count()) fail('malformed camera broke load');
  const b = await (await page.request.get(`http://127.0.0.1:${port}/api/board`)).json(); let puts=[];
  page.on('request', r => { if (r.url().includes('/api/board') && r.method()==='PUT') puts.push(r.postData()); });
  await page.request.put(`http://127.0.0.1:${port}/api/board`, { data:{width:160000,height:110000,version:b.version} }); await page.reload({waitUntil:'networkidle'}); await sleep(250);
  const huge=await snap(); if (!(huge.b.w>before.b.w && huge.b.h>before.b.h)) fail('finite huge board not visible'); if (puts.some(x=>/width.*0|height.*0/.test(x))) fail('zero dimension board PUT');
  const n=page.locator('.note'); await n.focus(); await n.press('Delete'); await sleep(200); if(await n.count()) fail('keyboard delete failed');
  const deleted=await (await page.request.get(`http://127.0.0.1:${port}/api/notes`)).json(); if(deleted.some(x=>x.title==='QA')) fail('delete not persisted');
  await page.getByRole('button',{name:'↶ Undo'}).click(); await sleep(200); if(!await page.locator('.note').count()) fail('note undo failed');
  await page.reload({waitUntil:'networkidle'}); if(!await page.locator('.note').count()) fail('note restore reload failed');
  if(errors.length) fail('browser errors: '+errors.join(' | '));
  console.log(JSON.stringify({pass:true, zoom, before, huge, camera:cam, boardPuts:puts})); await browser.close(); server.kill();
})().catch(e=>{console.error(e.stack||e); try{server.kill();}catch{} process.exitCode=1;});
